name: Python package

on: [ push ]
jobs:
  build:
    environment: GCP
    runs-on: ubuntu-latest
    container: python:3.9
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: xq-db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pg-password
        ports:
          - 5432:5432
        # Health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      GOOGLE_APPLICATION_CREDENTIALS: key.json
      CI: true
      POSTGRES_DB: xq-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg-password

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Create Google credentials file from secrets
        run: echo "${{secrets.SERVICE_ACCOUNT}}" | base64 --decode > $GOOGLE_APPLICATION_CREDENTIALS
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
#          pip install  ./src

      - name: Test with pytest
        run: pytest --cov=./ tests --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
